spawn:
  x: 0
  y: 0
  z: 0
  yaw: 0
  pitch: 0

chat:
  format: "$player $separator $message"
  separator: "»"
  colors: # Color names are in the ChatColor format, see https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/ChatColor.html.
    player: "GRAY"
    opPlayer: "GOLD"
    seperator: "DARK_GRAY"
    message: "RESET"

messages:
  targetOffline: "§4Doel is niet online!"
  gamemodeUsage: "§4/gamemode (creative/survival/spectator/adventure/0/1/2/3) (speler)"
  gamemodeSucces: "§aGedaan!"
  gamemodeChanged: "§aGamemode aangepast!"
  spawnSet: "§aSpawn set"
  kickAllPlayers: "§aKicking all players..."
  stopServer: "§aStopping server..."